spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: 825775381920-1f4f6nbk8uu32ahum1dtrj52ns58o16v.apps.googleusercontent.com
              client-secret: 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
                scope:
                  - openid
                  - profile
                  - email
        provider:
          auth0:
            # trailing slash is important!
          issuer-uri: https://accounts.google.com/o/oauth2/auth
